// // export { AuthModule as AuthModuleV2 } from './auth/auth.module';
// export { BranchModule as BranchModuleV2 } from './branch/branch.module';
// export { BarberModule as BarberModuleV2 } from './barber/barber.module';
// export { CategoryModule as CategoryModuleV2 } from './category/category.module';
// export { CashierModule as CashierModuleV2 } from './cashier/cashier.module';
// export { ClientModule as ClientModuleV2 } from './client/client.module';
// export { NotificationModule as NotificationModuleV2 } from './notification/notification.module';
// export { OrderModule as OrderModuleV2 } from './order/order.module';
// export { PromoCodeModule as PromoCodeModuleV2 } from './promo-code/promo-code.module';
// // export {ComplainModule as ComplainModuleV2} from './complain/complain.module';
// export { PointsModule as PointsModuleV2 } from './points/points.module';
// export { ProductModule as ProductModuleV2 } from './product/product.module';
// export { SettingsModule as SettingsModuleV2 } from './settings/settings.module';
// export { StaticModule as StaticModuleV2 } from './static/static.module';
// export { ServiceModule as ServiceModuleV2 } from './service/service.module';
// export { SlotModule as SlotModuleV2 } from './slot/slot.module';
// export { UserModule as UserModuleV2 } from './user/user.module';
